//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PDFReader.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_PDFReaderTYPE               130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_OUTLINEVIEW             133
#define ID_VIEW_LAYERVIEW               134
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define IDS_OUTLINE_VIEW                155
#define IDS_LAYER_VIEW                  156
#define IDR_OUTLINE_VIEW                175
#define IDR_LAYER_VIEW                  176
#define IDI_OUTLINE_VIEW                177
#define IDI_LAYER_VIEW                  178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDS_CLOSE                       195
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define ID_START_INTERFACE_DIALOG       317
#define IDB_LOG_BITMAP                  324
#define IDB_DELETE_BITMAP               327
#define IDB_EXIT_BITMAP                 329
#define IDB_OPEN_BITMAP                 330
#define IDD_PASSWORD_DIALOG             331
#define IDB_DELETE_BITMAP_GRAY          335
#define IDB_EXIT_BITMAP_GRAY            336
#define IDB_OPEN_BITMAP_GRAY            337
#define IDB_LOG_BITMAP_GRAY             338
#define IDC_CURSOR1                     339
#define IDC_CUR_CROSS                   339
#define IDR_GOTO_BAR                    340
#define IDD_PROPERTYDLG                 342
#define IDD_PROPERTYDLG_CREATION        343
#define IDD_PROPERTYDLG_INITIAL_VIEW    344
#define IDD_PROPERTYDLG_SECURITY        345
#define IDB_OUTLINE_BITMAP              347
#define IDB_BITMAP1                     348
#define IDB_OUTLINE_SEL_BITMAP          349
#define IDD_ANNOT_PROPERTY_DIALOG       350
#define IDD_ANNOT_AP_DIALOG             351
#define IDD_FREETEXT_AP_DIALOG          352
#define IDD_FREETEXT_GENERAL_DIALOG     353
#define ID_INTERFACE_VIEW_EXIT          1007
#define ID_INTERFACE_VIEW_OPEN          1008
#define IDC_INTERFACE_BITMAP            1010
#define IDC_INTERFACE_RECENT_LIST       1012
#define IDC_INTERFACE_DELETE_RECENT     1013
#define IDC_INTERFACE_OPEN_FILE         1014
#define IDC_INTERFACE_TEXT              1015
#define IDC_INTERFACE_EXIT_APP          1016
#define IDC_INTERFACE_EDIT_FOLDER       1017
#define IDC_PASSWORD_EDIT               1018
#define ID_PASSWORD_OK                  1019
#define IDC_CLOSEANNOTPROPERTY_BUTTON   1021
#define ID_PDF_HANDLE                   1022
#define IDC_ANNOT_PROPERTY_TAB          1022
#define ID_PDF_SEARCH                   1023
#define IDC_LOCKANNOT_CHECK             1023
#define ID_PDF_SELECT                   1024
#define ID_PDF_PSI                      1025
#define IDC_COLOR_BUTTON                1026
#define ID_PDF_ZOOM_OUT                 1027
#define IDC_OPACITY_STATIC              1028
#define ID_PDF_ZOOM_IN                  1029
#define IDC_OPACITY_EDIT                1030
#define ID_PDF_ROTATE_CW                1031
#define IDC_OPACITYPERCENT_STATIC       1032
#define ID_PDF_ROTATE_ACW               1033
#define IDC_OPACITY_SLIDER              1034
#define ID_PDF_CURRENT_INDEX            1035
#define IDC_NOTETYPE_STATIC             1036
#define ID_PDF_COUNT_INDEX              1037
#define IDC_PROPERTY_CANCEL             1038
#define IDC_PROPERTY_OK                 1039
#define IDC_CREATION_DESCRIPTION        1040
#define IDC_INI_VIEW_HIDEWINUI          1100
#define IDC_INI_VIEW_FITWIN             1101
#define IDC_INI_VIEW_CENTERWIN          1102
#define IDC_INI_VIEW_DIS_DOC_TITLE      1103
#define IDC_CREATION_EDIT_SUBJECT       1104
#define IDC_CREATION_EDIT_AUTHOR        1105
#define IDC_CREATION_EDIT_KEYWORDS      1106
#define IDC_CREATION_EDIT_TITLE         1108
#define IDC_INI_VIEW_CENTER_WIN         1109
#define IDC_INI_VIEW_HIDE_MENNU_BAR     1110
#define IDC_INI_VIEW_HIDE_WIN_UI        1111
#define IDC_INI_VIEW_DOC_TITLE          1112
#define IDC_STATIC_HIDETOOLBAR          1115
#define IDC_STATIC_FITWIDTH             1116
#define IDC_STATIC_CEN_WIN              1117
#define IDC_STATIC_HIDEMEN              1118
#define IDC_STATIC_HIDEWIN_UI           1119
#define IDC_STATIC_DOC_TITLE            1120
#define IDC_TAB                         1121
#define IDC_IDC_CREATION_ADVAVCED       1238
#define IDC_IDC_CREATION__FILES         1239
#define IDC_CREATION_TITLE              1240
#define IDC_CREATION_SUBJECT            1241
#define IDC_CREATION_AUTHOR             1242
#define IDC_CREATION_KEYWORDS           1243
#define IDC_CREATION_CREATOR            1244
#define IDC_CREATION_CREATED            1245
#define IDC_CREATION_MODIFIED           1246
#define IDC_CREATION_PRODUCER           1247
#define IDC_CREATION_FILE_SIZE          1248
#define IDC_CREATION_PAGE_SIZE          1249
#define IDC_CREATION_TOTAL_PAGES        1250
#define IDC_CREATION_EDIT_FILES         1251
#define IDC_CREATION_STATIC_CREATOR     1252
#define IDC_CREATION_STATIC_CREATED     1253
#define IDC_CREATION_STATIC_MODIFIED    1254
#define IDC_CREATION_STATIC_PRODUCER    1255
#define IDC_CREATION_STATIC_FILE_SIZE   1256
#define IDC_CREATION_STATIC_PAGE_SIZE   1257
#define IDC_CREATION_STATIC_TOTAL_PAGES 1258
#define IDC_SECURITY_DOC_SEC            1259
#define IDC_SECURITY_RES_SUM            1260
#define IDC_SECURITY_SEC_METHOD         1261
#define IDC_SECURITY_USER_PWD           1262
#define IDC_SECURITY_EN_LEVEL           1263
#define IDC_SECURITY_OWN_PWD            1264
#define IDC_SECURITY_PRINT              1265
#define IDC_SECURITY_MOD_DOC            1266
#define IDC_SECURITY_FILL_IN_FOR        1267
#define IDC_SECURITY_CON_EXT            1268
#define IDC_SECURITY_ACC_SUP            1269
#define IDC_SECURITY_DOC_ASS            1270
#define IDC_PROPERTYDLG_SEC_METHOD      1271
#define IDC_PROPERTYDLG_SEC_COM         1273
#define IDC_PROPERTYDLG_SEC_EDIT        1273
#define IDC_PROPERTYDLG_CHANGE_SETTINGS 1274
#define IDC_PROPERTYDLG_CHANGE          1274
#define IDC_SECURITY_STATIC_SEC_METHOD  1275
#define IDC_SECURITY_STATIC_USER_PWD    1276
#define IDC_SECURITY_STATIC_OWN_PWD     1277
#define IDC_SECURITY_STATIC_PRINT       1278
#define IDC_SECURITY_STATIC_MOD_DOC     1279
#define IDC_SECURITY_STATIC_CON_EXT     1280
#define IDC_SECURITY_STATIC_FILL_IN_FOR 1281
#define IDC_SECURITY_STATIC_DOC_ASS     1282
#define IDC_INI_VIEW_VIEP               1283
#define IDC_INI_VIEW_DIRECTION          1284
#define IDC_INI_VIEW_PAGEMODE           1285
#define IDC_INI_VIEW_NOTFULLMODE        1287
#define IDC_INI_VIEW_PRINT_SCALE        1288
#define IDC_INI_VIEW_PRINT_COPIES       1289
#define IDC_INI_VIEW_PRINT_SCALE2       1290
#define IDC_INI_VIEW_STATIC_PAGE_MODE   1292
#define IDC_INI_VIEW_STATIC_DIRECTION   1293
#define IDC_INI_VIEW_STATIC_PRINT_SCALE 1295
#define IDC_INI_VIEW_STATIC_PRINT_COPIES 1296
#define IDC_INI_VIEW_STATIC_PRINT_RANGES 1297
#define IDC_INI_VIEW_HIDETOOLBAR        1298
#define IDC_INI_VIEW_HIDEMENUBAR        1299
#define IDC_NOTETYPE_COMBO              1300
#define IDC_THICKNESS_STATIC            1334
#define IDC_AUTHOR_EDIT                 1335
#define IDC_THICKNESS_SPIN              1336
#define IDC_BORDERSTYPE_STATIC          1337
#define IDC_BORDERSTYPE_COMBO           1338
#define IDC_FREETEXTCOLOR_BUTTON        1339
#define IDC_FREETEXT_FILLCOLOR_STATIC   1340
#define IDC_FREETEXTFILLCOLOR_BUTTON    1341
#define IDC_FREETEXT_LINESTYPE_STATIC   1342
#define IDC_FREETEXTLINESTYLE_COMBO     1343
#define IDC_FREETEXTOPACITY_STATIC      1344
#define IDC_EDIT2                       1345
#define IDC_SUBJECT_EDIT                1345
#define IDC_FREETEXTOPACITY_SLIDER      1346
#define IDC_ANNOT_STATIC                1347
#define IDC_BORDERWIDTH_EDIT            1348
#define IDC_FREETEXTOPACITY_EDIT        1349
#define IDC_CREATIONDATE_STATIC         1350
#define IDC_MODDATE_STATIC              1352
#define IDD_FINDDLG                     1353
#define IDC_BUTTON_FIND_NEXT            1354
#define IDC_BUTTON_CANCLE               1355
#define IDC_EDIT_FINDTEXT               1357
#define IDC_CHECK_MATCHCASE             1358
#define IDC_CHECK_MATCHWHOLE            1359
#define IDC_RADIO_DOWN                  1360
#define IDC_RADIO_UP                    1361
#define IDC_CUR_CATCH                   2348
#define IDC_CUR_HAND                    2349
#define IDC_CUR_SELECTANNOT             2350
#define IDC_CURSOR2                     2352
#define IDC_CUR_POINT                   2352
#define IDR_ZOOM_TOOLBAR                2353
#define ID_WM_XFA_COPY                  10000
#define ID_WM_XFA_CUT                   10001
#define ID_WM_XFA_SELECTALL             10002
#define ID_WM_XFA_PASTE                 10003
#define ID_WM_XFA_DELETE                10004
#define ID_WM_XFA_SPELLCHECK            10005
#define ID_WM_XFA_TEXTSTYLE             10006
#define ID_WM_XFA_TEXTSTYLE_BOLD        10007
#define ID_WM_XFA_TEXTSTYLE_ITALIC      10008
#define ID_WM_XFA_TEXTSTYLE_UNDERLINE   10009
#define ID_WM_XFA_TEXTSTYLE_SUPERSCRIPT 10010
#define ID_WM_XFA_TEXTSTYLE_SUBSCRIPT   10011
#define ID_WM_XFA_TEXTSTYLE_CLEARSTYLE  10012
#define ID_WM_XFA_DESELECT              10013
#define ID_WM_XFA_UNDO                  10014
#define ID_WM_XFA_REDO                  10015
#define IDC_EDIT1                       21053
#define ID_OUTLINE_VIEW_MENU            32772
#define ID_TOOL_BAR                     32774
#define ID_VIEW_TOOL_BAR                32775
#define ID_VIEW_OUTLINE                 32776
#define ID_ANNOT_FREETEXT               32778
#define ID_ANNOT_HIGHLIGHT              32779
#define ID_ANNOT_UNDERLINE              32780
#define ID_ANNOT_NOTES                  32781
#define ID_ANNOT_LINK                   32782
#define ID_TOOL_ANNOTSELECT             32783
#define ID_VIEW_GOTOBAR                 32785
#define ID_DOCUMENT_PROPERTY            32786
#define ID_SLIDER_BUTTON                32788
#define ID_FIRST_PAGE                   32789
#define ID_PREV_PAGE                    32790
#define ID_CURRENT_PAGE                 32791
#define ID_NEXT_PAGE                    32792
#define ID_LAST_PAGE                    32793
#define ID_VIEW_ZOOMBAR                 32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2356
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         21054
#define _APS_NEXT_SYMED_VALUE           2310
#endif
#endif
